# Generated by Django 3.2 on 2022-03-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
